name: hackseeker

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ENV=${ENV:-production}
      - PUBLIC_POSTHOG_TOKEN=${PUBLIC_POSTHOG_TOKEN:-phc_oWXLqTi4LOraqGCjzyhWvNKUXSRg774cnKONPVZPlpm}
      - PUBLIC_POSTHOG_URL=${PUBLIC_POSTHOG_URL:-https://eu.i.posthog.com}
      - MEILI_URL=${MEILI_URL:-https://mvp-meili.cogitosoftware.nl}
      - LANGFUSE_PUBLIC_KEY=${LANGFUSE_PUBLIC_KEY:-pk-lf-ec076b61-09a8-40d4-9857-8bce360e67e0}
      - LANGFUSE_BASE_URL=${LANGFUSE_BASE_URL:-https://us.cloud.langfuse.com}
      - PUBLIC_POSTHOG=${PUBLIC_POSTHOG}
      - LITELLM_URL=${LITELLM_URL:-https://litellm.hackseeker.com}

      # SECRETS
      - LITELLM_API_KEY=${LITELLM_API_KEY}
      - PB_EMAIL=${PB_EMAIL}
      - PB_PASSWORD=${PB_PASSWORD}
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
      - LANGFUSE_SECRET_KEY=${LANGFUSE_SECRET_KEY}
      - STRIPE_API_KEY=${STRIPE_API_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - TG_ID=${TG_ID}
      - TG_TOKEN=${TG_TOKEN}
